DA: false
autocast: true
batchsize: 8
block: 4
color_jitter: false
data_dir: /root/dataset/University-Release/train
erasing_p: 0
fp16: false
gpu_ids: '0'
h: 256
kl_loss: false
lr: 0.01
moving_avg: 1.0
name: SafeNet-block4-lr0.01-sp2-bs8-ep200-s256-U1652
nclasses: 701
num_epochs: 200
num_worker: 4
pad: 0
sample_num: 2.0
share: true
steps:
- 70
- 110
train_all: false
triplet_loss: 0.0
use_gpu: true
views: 2
w: 256
warm_epoch: 0
